### ISSUE TITLE
Is dense copy truly needed?

### ISSUE THREAD

**Issue by marcsantiago** [sajari/regression#17]
https://github.com/sajari/regression/blob/c1eb7a8c6aca31d839ef0ca0effcef42e265acb1/regression.go#L174

couldn't 
```
qtr := q.T()
qtrd := mat.DenseCopyOf(qtr)
qty := new(mat.Dense)
qty.Mul(qtrd, observed)
```
be

```
qtr := q.T()
qty := new(mat.Dense)
qty.Mul(qtr, observed)
```

^ tests don't seem to break and I can't see a reason why a copy is being made the original `qtr` is never being mutated.  Moreover more memory is being used than necessary.  Should this be optimized? Was this an oversight? Is there intent that I'm missing? The only real thing `DenseCopyOf` seems to be doing is converting the  `Matrix` interface into the concrete type `*Dense`, which doesn't seem necessary because none of the underline values of Dense are being used explicitly.

**Comment by mish15** [comment]
@marcsantiago yes i don't see why not. @chewxy any reason you did this when changing it? There wasn't a copy here previously

**Comment by chewxy** [comment]
Habit. This is fine to optimize

**Comment by mish15** [comment]
cool thanks @chewxy 

@marcsantiago did you want to do a PR or we can just add this in the next round of changes

**Comment by marcsantiago** [comment]
You can go ahead and add it on your next round. I have it on a branch but
I'm still experimenting with it and want to avoid any kind of feature
creep.

**Comment by mish15** [comment]
no worries. Nice pickup by the way

**Comment by marcsantiago** [comment]
No problem I'm using the code at scale and my profilers picked on the high
memory allocations.
