### ISSUE TITLE
Function Run() has to have "division by 0" protection 

### ISSUE THREAD

**Issue by slavicamg** [sajari/regression#18]
Could someone make this change in this part of the code:
for i := n - 1; i >= 0; i-- {
		c[i] = qty.Get(i, 0)
		for j := i + 1; j < n; j++ {
			c[i] -= c[j] * reg.Get(i, j)
		}
// practically add these lines
		regValue := reg.Get(i, i)
		if regValue == 0 {
			return errors.New("Division by 0 is not allowed.")
		}
		c[i] /= regValue
// up to here
// replacing this line c[i] /= reg.Get(i, i)
	}

Thanks

**Comment by mish15** [comment]
@slavicamg thanks for this. Can you please submit a pull request with suggested changes?
