### ISSUE TITLE
Meaning of ¨initialised"

### ISSUE THREAD

**Issue by heiderich** [sajari/regression#24]
What is the meaning of `initialised` in the `Regression` type?

The error returned in

https://github.com/sajari/regression/blob/7932f0ed418e0217ddac466abba0f18c722835e8/regression.go#L55-L57

suggests that it becomes `true` when there is enough data. In 

https://github.com/sajari/regression/blob/7932f0ed418e0217ddac466abba0f18c722835e8/regression.go#L107-L109

it is set to `true` if  `len(r.data) > 2`. Why this condition?

The output of the following program 

```
package main

import (
	"fmt"
	"github.com/sajari/regression"
)

func main() {
	r := new(regression.Regression)
	r.SetObserved("obversed")
	r.SetVar(0, "var")
	r.Train(
		regression.DataPoint(1, []float64{1}),
		regression.DataPoint(2, []float64{2}),
		//regression.DataPoint(2, []float64{2}),
	)
	r.Run()

	fmt.Printf("Regression formula:\n%v\n", r.Formula)
	fmt.Printf("Regression:\n%s\n", r)
}
```

is

```
Regression formula:

Regression:
Not enough data points
```

With the line 

`		regression.DataPoint(2, []float64{2}),
`
instead of

`		//regression.DataPoint(2, []float64{2}),`

the output becomes

```
Regression formula:
Predicted = 0.00 + var*1.00
Residuals:
observed|	Predicted|	Residual
1.00|	1.00|	-0.00
2.00|	2.00|	0.00
2.00|	2.00|	0.00


Regression:
obversed|	var
1.00|	1.00
2.00|	2.00
2.00|	2.00

N = 3
Variance observed = 0.2222222222222222
Variance Predicted = 0.22222222222222196
R2 = 0.9999999999999989
```

I would not expect any of these outputs.

**Comment by mish15** [comment]
From memory the QR transform fails if a) there is not enough data points and b) if one column is all zeros. This was pretty hacky.
