### ISSUE TITLE
Error at qr.QTo and qr.RTo

### ISSUE THREAD

**Issue by jefersonprediza** [sajari/regression#28]
Hi,

I recieved the error bellow when I tried build my app, because this pull https://github.com/gonum/gonum/pull/1090

go build
# github.com/sajari/regression
../../../github.com/sajari/regression/regression.go:170:13: qr.QTo(nil) used as value
../../../github.com/sajari/regression/regression.go:171:15: qr.RTo(nil) used as value

To fix it, i change your code in regression.go to:
	
var q, reg mat.Dense
qr.QTo(&q)
qr.RTo(&reg)

**Comment by mish15** [comment]
fixed

**Comment by vadymc** [comment]
@mish15 Hi, any chance you could also create a release tag for that? While importing through `go mod` it still pulls the v1.0.0, which still has the bug.

Thanks
