### ISSUE TITLE
[Feature Request] An API to get the number of variables.

### ISSUE THREAD

**Issue by updogliu** [sajari/regression#29]
Requesting an API to get the number of variables, i.e. the number of coefficients. Implementation-wise, just `return len(r.coeff)`.

It would be even better if there was an API to get the coefficients as a `[]float64`.

**Comment by mish15** [comment]
The number of coefficients matches the number of variables + crosses though, so this should already be known right? 

The coefficients as a slice should be easy enough. Happy to take a PR on that if you're interested?
