### ISSUE TITLE
It would be nice to add the ability to enforce zero intercept

### ISSUE THREAD

**Issue by jumbleview** [sajari/regression#5]
Seems to be  be nice package with clean interface. The only problem for me to use:  I did not find the way to enforce line to pass through the origin (in other word zero intercept) as LINEST in Excel  or Calc allows.

**Comment by mish15** [comment]
We're open to pull requests if you want to implement? It's not a high priority for us as we don't need it currently.

**Comment by mish15** [comment]
@jumbleview did you want to keep this open? It's likely not too hard, but not a focus for us at present.
