### ISSUE TITLE
Support automatically generating feature crosses

### ISSUE THREAD

**Issue by twitchyliquid64** [sajari/regression#6]
Heya,

Sick presentation Hamish.

Considering adding support for feature crosses (square, cubic, etc)? I think it would be pretty easy. I would also boost the dank score of the repo.

I think it could be done as a thin wrapper function around DataPoint().

**Comment by mish15** [comment]
@twitchyliquid64 Thanks! Feature crosses would definitely be useful. You could wrap the data point function as you say. Did you want to have a crack at it?

What is a dank score?

**Comment by twitchyliquid64** [comment]
Ill have a crack at it :) hopefully over the next two days.

Dankness is hard to quantify, but I think this is a step in the right direction.

**Comment by twitchyliquid64** [comment]
See PR xD
