### ISSUE TITLE
How does this actually work

### ISSUE THREAD

**Issue by twitchyliquid64** [sajari/regression#8]
I was expecting a hot loop with stochastic gradient descent or something but then I saw this in run():

```go
c := make([]float64, n)
for i := n - 1; i >= 0; i-- {
	c[i] = qty.Get(i, 0)
	for j := i + 1; j < n; j++ {
		c[i] -= c[j] * reg.Get(i, j)
	}
	c[i] /= reg.Get(i, i)
}
```
That seems way too efficient for ML.

Point me to a wikipedia on this algorithm ? :D

**Comment by mish15** [comment]
QR decomposition from memory

**Comment by twitchyliquid64** [comment]
Cheerzies xD
